### PR TITLE
Feature: Style basic lander page

### PR DESCRIPTION
**Pull request by paulathevalley**
Resolves https://github.com/FormidableLabs/formidable-landers/issues/125

/cc @ebrillhart @rgerstenberger @bmathews 

screencapture-localhost-3000-1470089993398

screencapture-localhost-3000-1470090237566

### CODE REVIEW

**Comment by ebrillhart** [comment]
I think this looks awesome

**Comment by rgerstenberger** [comment]
Nice! We'll also need linux download.

**Comment by rgerstenberger** [comment]
Looks great! :shipit:

**Comment by bmathews** [comment]
:+1: Looks great!

**Comment by paulathevalley** [comment]
@rgerstenberger Ok! I will merge this for now and when the download links are available, they can get updated in another PR.

**Pull request merged**
